// Sample Next.js project files
export const DEFAULT_NEXTJS_FILES = {
  '/app/page.tsx': `export default function Home() {
    return (
      <main className="flex min-h-screen flex-col items-center justify-between p-24">
        <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm flex">
          <p className="fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit">
            Get started by editing&nbsp;
            <code className="font-mono font-bold">app/page.tsx</code>
          </p>
        </div>
  
        <div className="relative flex place-items-center">
          <h1 className="text-4xl font-bold">Welcome to Next.js</h1>
        </div>
  
        <div className="mb-32 grid text-center lg:max-w-5xl lg:w-full lg:mb-0 lg:grid-cols-3 lg:text-left">
          <div className="group rounded-lg border border-transparent px-5 py-4 transition-colors border-gray-300 bg-gray-100 dark:border-neutral-700 dark:bg-neutral-800/30">
            <h2 className="mb-3 text-2xl font-semibold">
              Docs
            </h2>
            <p className="m-0 max-w-[30ch] text-sm opacity-50">
              Find in-depth information about Next.js features and API.
            </p>
          </div>
        </div>
      </main>
    );
  }`,
  '/app/layout.tsx': `import type { Metadata } from 'next';
  import { Inter } from 'next/font/google';
  import './globals.css';
  
  const inter = Inter({ subsets: ['latin'] });
  
  export const metadata: Metadata = {
    title: 'Next.js App',
    description: 'Generated by web9',
  };
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    );
  }`,
  '/app/globals.css': `@tailwind base;
  @tailwind components;
  @tailwind utilities;
  
  :root {
    --foreground-rgb: 0, 0, 0;
    --background-rgb: 255, 255, 255;
  }
  
  @media (prefers-color-scheme: dark) {
    :root {
      --foreground-rgb: 255, 255, 255;
      --background-rgb: 0, 0, 0;
    }
  }
  
  body {
    color: rgb(var(--foreground-rgb));
    background: rgb(var(--background-rgb));
  }`,
  '/components/button.tsx': `import { ButtonHTMLAttributes } from 'react';
  
  interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
    variant?: 'primary' | 'secondary' | 'outline';
    size?: 'sm' | 'md' | 'lg';
  }
  
  export default function Button({
    children,
    variant = 'primary',
    size = 'md',
    className,
    ...props
  }: ButtonProps) {
    const baseStyles = 'inline-flex items-center justify-center rounded-md font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2';
    
    const variantStyles = {
      primary: 'bg-blue-600 text-white hover:bg-blue-700',
      secondary: 'bg-gray-200 text-gray-900 hover:bg-gray-300',
      outline: 'border border-gray-300 bg-transparent hover:bg-gray-100',
    };
    
    const sizeStyles = {
      sm: 'h-8 px-3 text-xs',
      md: 'h-10 px-4 text-sm',
      lg: 'h-12 px-6 text-base',
    };
    
    const classes = \`\${baseStyles} \${variantStyles[variant]} \${sizeStyles[size]} \${className || ''}\`;
    
    return (
      <button className={classes} {...props}>
        {children}
      </button>
    );
  }`,
  '/components/card.tsx': `interface CardProps {
    title?: string;
    children: React.ReactNode;
    className?: string;
  }
  
  export default function Card({ title, children, className = '' }: CardProps) {
    return (
      <div className={\`bg-white shadow rounded-lg overflow-hidden \${className}\`}>
        {title && (
          <div className="border-b border-gray-200 px-4 py-3">
            <h3 className="text-lg font-medium text-gray-900">{title}</h3>
          </div>
        )}
        <div className="px-4 py-5">{children}</div>
      </div>
    );
  }`,
};

export const SIMPLE_PROJECT_TWO = {
  '/app/page.tsx': `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center">
      <h1 className="text-4xl font-bold">Hello Coconut</h1>
    </main>
  );
}`,
  '/app/layout.tsx': `import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Simple Test',
  description: 'Testing Sandpack',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`,
  '/app/globals.css': `body {
  margin: 0;
  padding: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
}`,
};

// Sample project structure for demonstration
export const SAMPLE_PROJECT = {
  '/app/page.tsx': `export default function Home() {
    return (
      <main className="flex min-h-screen flex-col items-center justify-between p-24">
        <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm flex">
          <p className="fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit">
            Generated by web9
          </p>
        </div>
  
        <div className="relative flex place-items-center">
          <h1 className="text-4xl font-bold">Welcome to the Bakery</h1>
        </div>
  
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 w-full max-w-5xl">
          <ProductCard 
            title="Sourdough Bread" 
            price="$4.99" 
            description="Our signature sourdough with a perfect crust" 
          />
          <ProductCard 
            title="Croissant" 
            price="$3.50" 
            description="Buttery, flaky, and perfectly baked" 
          />
          <ProductCard 
            title="Chocolate Cake" 
            price="$24.99" 
            description="Rich chocolate cake with ganache frosting" 
          />
        </div>
      </main>
    );
  }`,
  '/app/layout.tsx': `import type { Metadata } from 'next';
  import { Inter } from 'next/font/google';
  import './globals.css';
  
  const inter = Inter({ subsets: ['latin'] });
  
  export const metadata: Metadata = {
    title: 'Bakery Landing Page',
    description: 'A delicious bakery with fresh bread and pastries',
  };
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    );
  }`,
  '/app/globals.css': `@tailwind base;
  @tailwind components;
  @tailwind utilities;
  
  :root {
    --foreground-rgb: 0, 0, 0;
    --background-rgb: 255, 255, 255;
  }
  
  body {
    color: rgb(var(--foreground-rgb));
    background: rgb(var(--background-rgb));
  }`,
  '/components/ProductCard.tsx': `interface ProductCardProps {
    title: string;
    price: string;
    description: string;
    image?: string;
  }
  
  export default function ProductCard({ 
    title, 
    price, 
    description, 
    image = '/product-placeholder.jpg'
  }: ProductCardProps) {
    return (
      <div className="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow">
        <div className="h-48 bg-gray-200"></div>
        <div className="p-4">
          <div className="flex justify-between items-start">
            <h3 className="text-lg font-semibold">{title}</h3>
            <span className="font-bold text-green-600">{price}</span>
          </div>
          <p className="mt-2 text-gray-600 text-sm">{description}</p>
          <button className="mt-4 w-full bg-amber-600 text-white py-2 rounded hover:bg-amber-700 transition-colors">
            Add to Cart
          </button>
        </div>
      </div>
    );
  }`,
  '/components/Header.tsx': `export default function Header() {
    return (
      <header className="bg-amber-700 text-white shadow-md">
        <div className="container mx-auto px-4 py-3 flex justify-between items-center">
          <div className="flex items-center">
            <span className="text-2xl font-bold">Fresh Bakery</span>
          </div>
          
          <nav>
            <ul className="flex space-x-6">
              <li><a href="#" className="hover:text-amber-200">Home</a></li>
              <li><a href="#" className="hover:text-amber-200">Products</a></li>
              <li><a href="#" className="hover:text-amber-200">About</a></li>
              <li><a href="#" className="hover:text-amber-200">Contact</a></li>
            </ul>
          </nav>
          
          <div>
            <button className="bg-white text-amber-700 px-4 py-2 rounded-md hover:bg-amber-100">
              Order Now
            </button>
          </div>
        </div>
      </header>
    );
  }`,
};

export const APP_ROUTER_PROJECT = {
  // App directory files
  '/app/page.tsx': `export default function Home() {
      return (
        <main className="flex min-h-screen flex-col items-center justify-center">
          <h1 className="text-4xl font-bold">Hello Coconut</h1>
        </main>
      );
    }`,
  '/app/layout.tsx': `import type { Metadata } from 'next';
      import './globals.css';
      
      export const metadata: Metadata = {
        title: 'App Router Example',
        description: 'Using App Router with Sandpack',
      };
      
      export default function RootLayout({
        children,
      }: {
        children: React.ReactNode;
      }) {
        return (
          <html lang="en">
            <body>{children}</body>
          </html>
        );
      }`,
  '/app/globals.css': `body {
      margin: 0;
      padding: 0;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    }`,

  // Next.js config files
  '/next.config.js': `/** @type {import('next').NextConfig} */
      const nextConfig = {
        reactStrictMode: true,
      };
      
      module.exports = nextConfig;`,
  '/package.json': `{
      "name": "next-app",
      "version": "0.1.0",
      "private": true,
      "scripts": {
        "dev": "next dev",
        "build": "next build",
        "start": "next start"
      },
      "dependencies": {
        "next": "^14.0.0",
        "react": "^18.2.0",
        "react-dom": "^18.2.0"
      },
      "devDependencies": {
        "@types/node": "^20.8.0",
        "@types/react": "^18.2.0",
        "typescript": "^5.2.0"
      }
    }`,
  '/tsconfig.json': `{
      "compilerOptions": {
        "target": "es5",
        "lib": ["dom", "dom.iterable", "esnext"],
        "allowJs": true,
        "skipLibCheck": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "noEmit": true,
        "esModuleInterop": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "jsx": "preserve",
        "incremental": true,
        "plugins": [
          {
            "name": "next"
          }
        ],
        "paths": {
          "@/*": ["./*"]
        }
      },
      "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
      "exclude": ["node_modules"]
    }`,
};

export const ROUTER_TEST_TWO = {
  '/app/page.tsx': `
      export default function Page() {
        return <h1>Hello from App Router!</h1>;
      }
    `,
  '/app/layout.tsx': `
      export default function RootLayout({ children }) {
        return (
          <html>
            <body>
              {children}
            </body>
          </html>
        );
      }
    `,
};

// export const NEXT_APP_ROUTER_TEMPLATE_THREE = {
//     '/app/page.js': {
//       code: `export default function HomePage() {
//     return (
//       <main>
//         <h1>Hello from the App Router!</h1>
//       </main>
//     )
//   }`,
//       active: true,
//     },
//     // ... other files
//   },
//   options: {
//     activeFile: '/app/page.js';
//     visibleFiles: ['/app/page.js', '/app/layout.js', '/next.config.js'];
//   },
//   customSetup: {
//     dependencies: {
//       next: '^13.4.1';
//       react: '^18.2.0';
//       'react-dom': '^18.2.0';
//     };
//     entry: '/app/page.js';
//   };
